<!DOCTYPE html>
<html lang="en">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Maintainance Running</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{{ asset('public/images/icons8-gradient-line-50.png') }}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.js"></script>
  
  <style>
              /* ----------------------------------------------
         * Generated by Animista on 2020-1-20 22:0:23
         * Licensed under FreeBSD License.
         * See http://animista.net/license for more info. 
         * w: http://animista.net, t: @cssanimista
         * ---------------------------------------------- */
        
        /**
         * ----------------------------------------
         * animation rotate-scale-up
         * ----------------------------------------
         */
        @-webkit-keyframes rotate-scale-up {
          0% {
            -webkit-transform: scale(1) rotateZ(0);
                    transform: scale(1) rotateZ(0);
          }
          50% {
            -webkit-transform: scale(2) rotateZ(180deg);
                    transform: scale(2) rotateZ(180deg);
          }
          100% {
            -webkit-transform: scale(1) rotateZ(360deg);
                    transform: scale(1) rotateZ(360deg);
          }
        }
        @keyframes rotate-scale-up {
          0% {
            -webkit-transform: scale(1) rotateZ(0);
                    transform: scale(1) rotateZ(0);
          }
          50% {
            -webkit-transform: scale(2) rotateZ(180deg);
                    transform: scale(2) rotateZ(180deg);
          }
          100% {
            -webkit-transform: scale(1) rotateZ(360deg);
                    transform: scale(1) rotateZ(360deg);
          }
        }
        .rotate-scale-up {
        	-webkit-animation: rotate-scale-up 0.65s linear infinite both;
        	        animation: rotate-scale-up 0.65s linear infinite both;
        }

  </style>
</head>
<body>

  
<div class="container-fluid">
    <div class="row bg-info">
        <div class="col-md-12">
            <img src="{{ asset('public/images/icons8-gradient-line-50.png') }}" class="float-left mt-3 mb-3 rotate-scale-up" alt="">
            <img src="{{ asset('public/images/icons8-gradient-line-50.png') }}" class="float-right mt-3 mb-3 rotate-scale-up" alt="">
            <h4 class="text-white text-center">Server Maintainance Running.... <br>Please Try Again later</h4>
            <img src="{{ asset('public/images/maintain.jpg') }}" height="auto" width="100%" alt="">
        </div>
    </div>
</div>

</body>
</html>
