---
deployment:
  tasks:
    # your repo root
    - export REPO_DIR=/home/wachoqfr/repository/core

    # first target
    - export DEPLOY_DIR1=/home/wachoqfr/blessed1.wacheseh.com
    - rsync -av --delete-after \
      --exclude='.git' \
      --exclude='.cpanel.yml' \
      "$REPO_DIR"/ "$DEPLOY_DIR1"/

    # second target
    - export DEPLOY_DIR2=/home/wachoqfr/blessed2.wacheseh.com
    - rsync -av --delete-after \
      --exclude='.git' \
      --exclude='.cpanel.yml' \
      "$REPO_DIR"/ "$DEPLOY_DIR2"/
